### ISSUE TITLE
how to use this mod?

### ISSUE THREAD

**Issue by Dann50** [wanomaniac/scmc#1]
i dont know java so i have no idea what i'm doing and there is no guides out there about this mod

**Comment by wanomaniac** [comment]
Sorry if i confused you in the readme documentation of this mod, let me
basically explain what you are supposed to do with this mod.
Note: This is not a mod for your minecraft client or the game itself, its
for your server. Please use ServerModMenu instead of SCMC

You don't have to build this project, there are download links available in
modrinth, github releases & forge.
I assume you already downloaded the mod & put it into your fabric server
(1.20.1 at least for now).
You can download the mod from the releases page of github or modrinth (or
forge)
Try starting the server and see if everything works. It should.

Now that's all the work you have to do to start a SCMC server network for
ServerModMenu to look & register.
Unless you want to change a few things. You can do so in the
/config/SCMC.js file in your server's folder.
Please read the comments in the config file to better understand the
purpose of this code.
If you need more help, let me know!

**Comment by wanomaniac** [comment]
no response for 3 weeks, closing this.
